server:
  port: 8081
#选择要激活的环境模块
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  config:
    name: dev
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: prod