#关闭模板引擎的缓存
spring:
  thymeleaf:
    cache: false


  # 配置问价你的真实位置i18n.login
  messages:
    basename: i18n.login
  mvc:
    format:
      date: yyyy-MM-dd
server:
  servlet:
    context-path: /wang


